# Copyright (c) 2018-present. This file is part of V-Sekai https://v-sekai.org/.
# SaracenOne & K. S. Ernest (Fire) Lee & Lyuma & MMMaellon & Contributors
# status_codes.gd
# SPDX-License-Identifier: MIT

const STATUS_CODE_PENDING = 0
const STATUS_CODE_NO_USERNAME = 1
const STATUS_CODE_NO_EMAIL = 2
const STATUS_CODE_NO_PASSWORD = 3
const STATUS_CODE_PASSWORD_MISMATCH = 4

const STATUS_STRING_MAP: Dictionary = {STATUS_CODE_PENDING: "TR_MENU_STATUS_CODE_PENDING", STATUS_CODE_NO_USERNAME: "TR_MENU_STATUS_CODE_NO_USERNAME", STATUS_CODE_NO_EMAIL: "TR_MENU_STATUS_CODE_NO_EMAIL", STATUS_CODE_NO_PASSWORD: "TR_MENU_STATUS_CODE_NO_PASSWORD", STATUS_CODE_PASSWORD_MISMATCH: "TR_MENU_STATUS_CODE_PASSWORD_MISMATCH"}
