[[actions]]
name = "Play"
path = "v_sekai_windows.exe"
platform = "windows"
args = ["--xr-mode on"]
[[actions]]
name = "Play Editor"
path = "v_sekai_windows.exe"
platform = "windows"
args = ["--project-manager"]
[[actions]]
name = "Play in Desktop"
path = "v_sekai_windows.exe"
platform = "windows"
args = ["--xr-mode off"]
[[actions]]
name = "V-Sekai Github project"
platform = "windows"
path = "https://github.com/V-Sekai/v-sekai-game"
