name: Bug report
description: Report a bug in V-Sekai
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      - Write a descriptive issue title above.
- type: input
  attributes:
    label: V-Sekai version
    description: >
      Specify the Git commit hash if using a development or non-official build.
      If you use a custom build, please test if your issue is reproducible in official builds too.
    placeholder: groups-4.0.groups-4.0.0.ca34356e.247.281-2022-03-08T04:26:30+00:00
  validations:
    required: false

- type: input
  attributes:
    label: System information
    description: |
      Specify the OS version, and when relevant hardware information.
      For graphics-related issues, specify the GPU model, driver version, and the rendering backend (GLES2, GLES3, Vulkan).
    placeholder: Windows 10, GLES3, Intel HD Graphics 620 (27.20.100.9616)
  validations:
    required: false

- type: textarea
  attributes:
    label: Issue description
    description: |
      You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      List of steps or sample code that reproduces the issue. Having reproducible issues is a prerequisite for contributors to be able to solve them.
      If you include a minimal reproduction project below, you can detail how to use it here.
  validations:
    required: true

- type: textarea
  attributes:
    label: Minimal reproduction project (For SDK or engine issues)
    description: |
      A small V-Sekai project which reproduces the issue. Highly recommended to speed up troubleshooting.
      Drag and drop a ZIP archive to upload it.
  validations:
    required: false
