name: Build Godot
description: Build Godot with the provided options.
inputs:
  target:
    description: Build target (editor, template_release, template_debug).
    default: "editor"
  tests:
    description: Unit tests.
    default: false
  build-arch:
    description: Arch.
    default: false
  deploy:
    description: Deploy game.
    default: false
  deploy-arch:
    description: Deploy arch.
    default: false
  deploy-platform:
    description: Deploy game platform.
    required: false
  deploy-platform-target:
    description: Deploy game target.
    required: false
  platform:
    description: Target platform.
    required: false
  sconsflags:
    default: ""
  scons-cache:
    description: The scons cache path.
    default: "${{ github.workspace }}/.scons-cache/"
  scons-cache-limit:
    description: The scons cache size limit.
    # actions/cache has 10 GiB limit, and GitHub runners have a 14 GiB disk.
    # Limit to 7 GiB to avoid having the extracted cache fill the disk.
    default: 7168
runs:
  using: "composite"
  steps:
    - name: Scons Build
      shell: bash
      env:
        SCONSFLAGS: ${{ inputs.sconsflags }}
        SCONS_CACHE: ${{ inputs.scons-cache }}
        SCONS_CACHE_LIMIT: ${{ inputs.scons-cache-limit }}
      run: |
        echo "Building with flags:" platform=${{ inputs.platform }} target=${{ inputs.target }} tests=${{ inputs.tests }} ${{ env.SCONSFLAGS }}

        if [ "${{ inputs.target }}" != "editor" ]; then
          # Ensure we don't include editor code in export template builds.
          rm -rf editor
        fi

        if [ "${{ github.event.number }}" != "" ]; then
          # Set build identifier with pull request number if available. This is displayed throughout the editor.
          export BUILD_NAME="gh-${{ github.event.number }}"
        else
          export BUILD_NAME="gh"
        fi

        if [[ "${{ inputs.deploy }}" == "true" ]]; then
          export PLATFORM=${{ inputs.deploy-platform }}
          export TARGET=${{ inputs.deploy-platform-target }}
          export ARCH=${{ inputs.deploy-arch }}
        else
          export PLATFORM=${{ inputs.platform }}
          export TARGET=${{ inputs.target }}
          export ARCH=${{ inputs.build-arch }}
        fi

        scons platform=$PLATFORM target=$TARGET tests=${{ inputs.tests }} ${{ env.SCONSFLAGS }} arch=$ARCH
        ls -l bin/