name: Upload Godot artifact
description: Upload the Godot artifact.
inputs:
  name:
    description: The artifact name.
    default: "${{ github.job }}"
  path:
    description: The path to upload.
    required: true
    default: "godot/bin/*"
runs:
  using: "composite"
  steps:
    - name: Upload Godot Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: 14

    - name: Prepare artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        export TARGET=${{ inputs.name }}
        mkdir $TARGET
        cp -r ${{ inputs.path }} $TARGET/
        7z a -r $TARGET.zip $TARGET
      shell: bash

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ inputs.name }}.zip