name: Setup python and scons
description: Setup python, install the pip version of scons.
inputs:
  python-version:
    description: The python version to use.
    default: "3.x"
  python-arch:
    description: The python architecture.
    default: "x64"
runs:
  using: "composite"
  steps:
    # Use python 3.x release (works cross platform)
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: ${{ inputs.python-version }}
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: ${{ inputs.python-arch }}

    - name: Setup scons
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons
        scons --version

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          target: x86_64-pc-windows-gnu
          components: rustfmt, clippy

    - name: Setup mingw and mingw openssl
      shell: bash
      run: |
        sudo add-apt-repository ppa:tobydox/mingw-w64
        sudo apt update
        sudo apt install -y openssl-mingw-w64 

    - name: Checkout modules repo
      uses: actions/checkout@v3
      with:
        repository: v-sekai/godot-modules-groups
        path: vsk_modules
        submodules: recursive
        ref: b34ff3300fbc6d1e840bc40fe930a372041bd6e9

    - name: Checkout godot engine repo
      uses: actions/checkout@v3
      with:
        repository: v-sekai/godot
        path: godot
        ref: 0c87f07367376fe3ebb0a99ef50f89380b69076f
