name: pre-commit

on:
  pull_request:
  push:
    branches:
      - rx

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      #- name: Install pre-commit
      #  run: pip install pre-commit

      #- name: Run pre-commit
      #  run: pre-commit run --all-files

      - name: Run custom linter
        run: bash .github/workflows/custom_linter.sh
